//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeödevi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayitol
    {
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string ceptel { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
        public string sifretekrari { get; set; }
        public string Role { get; set; }
    }
}
