//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeödevi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eticaretEntities5 : DbContext
    {
        public eticaretEntities5()
            : base("name=eticaretEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminlogin> adminlogin { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<kayitol> kayitol { get; set; }
        public virtual DbSet<markalar> markalar { get; set; }
        public virtual DbSet<sepet> sepet { get; set; }
        public virtual DbSet<sipariş> sipariş { get; set; }
        public virtual DbSet<sliderüst> sliderüst { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ürünler> ürünler { get; set; }
    }
}
