//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeödevi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ürünler
    {
        public int ürünid { get; set; }
        public string ürünadi { get; set; }
        public Nullable<int> ürünmarka { get; set; }
        public string ürünözellikleri { get; set; }
        public Nullable<int> ürünkategori { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string stok { get; set; }
        public string ürünresmi { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual markalar markalar { get; set; }
    }
}
